controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# diffbot_base_controller:
#   ros__parameters:
#     type: diff_drive_controller/DiffDriveController

#     left_wheel_names: ["left_velocity_pid_controller/left_pitch_pid_controller/left_wheel_joint"]
#     right_wheel_names: ["right_velocity_pid_controller/right_pitch_pid_controller/right_wheel_joint"]

#     wheel_separation: 0.4368
#     #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
#     wheel_radius: 0.072

#     wheel_separation_multiplier: 1.0
#     left_wheel_radius_multiplier: 1.0
#     right_wheel_radius_multiplier: 1.0

#     publish_rate: 50.0
#     odom_frame_id: odom
#     base_frame_id: base_link
#     pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
#     twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

#     open_loop: true
#     # enable_odom_tf: true
#     position_feedback: false

#     cmd_vel_timeout: 0.5
#     #publish_limited_velocity: true
#     #velocity_rolling_window_size: 10

#     # Velocity and acceleration limits
#     # Whenever a min_* is unspecified, default to -max_*
#     linear.x.has_velocity_limits: true
#     linear.x.has_acceleration_limits: true
#     linear.x.has_jerk_limits: false
#     linear.x.max_velocity: 8.0
#     linear.x.min_velocity: -8.0
#     linear.x.max_acceleration: 2.0
#     linear.x.min_acceleration: -2.0
#     linear.x.max_jerk: 0.0
#     linear.x.min_jerk: 0.0

#     angular.z.has_velocity_limits: true
#     angular.z.has_acceleration_limits: true
#     angular.z.has_jerk_limits: false
#     angular.z.max_velocity: 8.0
#     angular.z.min_velocity: -8.0
#     angular.z.max_acceleration: 1.0
#     angular.z.min_acceleration: -1.0
#     angular.z.max_jerk: 0.0
#     angular.z.min_jerk: 0.0

left_add_feedforward_controller:
  ros__parameters:
    type: rocko_env/AddFeedforwardController
    interfaces: [left_wheel_joint/velocity]
    feedforward_topic_name: "left_feedforward"

left_pitch_pid_controller:
  ros__parameters:
    type: pid_controller/PidController
    dof_names:
      - left_add_feedforward_controller/left_wheel_joint

    command_interface: velocity

    reference_and_state_interfaces: ["pitch"]
    reference_and_state_dof_names:
      - left_wheel_joint

    gains:
      left_add_feedforward_controller/left_wheel_joint:   {p: 8.0, i: 0.3, d: 0.3, i_clamp_max: 10.0, i_clamp_min: -10.0}

left_velocity_pid_controller:
  ros__parameters:
    type: pid_controller/PidController
    dof_names:
      - left_pitch_pid_controller/left_wheel_joint
    
    command_interface: pitch

    reference_and_state_interfaces: ["velocity"]
    reference_and_state_dof_names:
      - left_wheel_joint

    gains:
      left_pitch_pid_controller/left_wheel_joint:   {p: 0.0, i: 0.0, d: 0.0, i_clamp_max: 5.0, i_clamp_min: -5.0}

right_add_feedforward_controller:
  ros__parameters:
    type: rocko_env/AddFeedforwardController
    interfaces: [right_wheel_joint/velocity]
    feedforward_topic_name: "right_feedforward"

right_pitch_pid_controller:
  ros__parameters:
    type: pid_controller/PidController
    dof_names:
      - right_add_feedforward_controller/right_wheel_joint

    command_interface: velocity

    reference_and_state_interfaces: ["pitch"]
    reference_and_state_dof_names:
      - right_wheel_joint

    gains:
      right_add_feedforward_controller/right_wheel_joint:  {p: 8.0, i: 0.3, d: 0.3, i_clamp_max: 10.0, i_clamp_min: -10.0}

right_velocity_pid_controller:
  ros__parameters:
    type: pid_controller/PidController
    dof_names:
      - right_pitch_pid_controller/right_wheel_joint
    
    command_interface: pitch

    reference_and_state_interfaces: ["velocity"]
    reference_and_state_dof_names:
      - right_wheel_joint

    gains:
      right_pitch_pid_controller/right_wheel_joint:  {p: 0.0, i: 0.0, d: 0.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
