controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffbot_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.10
    wheel_radius: 0.144

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.max_velocity: 16.0
    linear.x.min_velocity: -16.0
    linear.x.max_acceleration: 3.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.max_velocity: 5.0
    angular.z.min_velocity: -5.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0