controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_add_feedforward_controller:
  ros__parameters:
    type: rocko_env/AddFeedforwardController
    interfaces: [left_wheel_joint/velocity]
    feedforward_topic_name: "left_feedforward"

right_add_feedforward_controller:
  ros__parameters:
    type: rocko_env/AddFeedforwardController
    interfaces: [right_wheel_joint/velocity]
    feedforward_topic_name: "right_feedforward"

pitch_pid_controller:
  ros__parameters:
    type: pid_controller/PidController
    dof_names:
      - left_add_feedforward_controller/left_wheel_joint
      - right_add_feedforward_controller/right_wheel_joint

    command_interface: velocity

    reference_and_state_interfaces: ["pitch"]
    reference_and_state_dof_names:
      - left_wheel_joint
      - right_wheel_joint

    gains:
      left_add_feedforward_controller/left_wheel_joint:   {p: 4.0, i: 0.0, d: 0.0, i_clamp_max: 10.0, i_clamp_min: -10.0}
      right_add_feedforward_controller/right_wheel_joint:   {p: 4.0, i: 0.0, d: 0.0, i_clamp_max: 10.0, i_clamp_min: -10.0}

velocity_pid_controller:
  ros__parameters:
    type: pid_controller/PidController
    dof_names:
      - pitch_pid_controller/left_wheel_joint
      - pitch_pid_controller/right_wheel_joint
    
    command_interface: pitch

    reference_and_state_interfaces: ["velocity"]
    reference_and_state_dof_names:
      - left_wheel_joint
      - right_wheel_joint

    gains:
      pitch_pid_controller/left_wheel_joint:   {p: 0.0, i: 0.0, d: 0.0, i_clamp_max: 5.0, i_clamp_min: -5.0} # 2.0, 0.1, 0.0
      pitch_pid_controller/right_wheel_joint:   {p: 0.0, i: 0.0, d: 0.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
